# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::CI; end
module Bundler::FetchMetadata; end
module Bundler::MatchMetadata; end
module Set::SubclassCompatible; end
module Set::SubclassCompatible::ClassMethods; end
module SolidQueue::Execution::GeneratedAssociationMethods; end
